services:
  # Web Service
  - type: web
    name: MyPortfolio
    env: docker
    plan: free
    buildCommand: "docker build -t MyPortfolio ."
    startCommand: "docker run -p $PORT:8080 MyPortfolio"
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:${PORT}

# Configuração do banco de dados (se precisar no futuro)
databases:
  - name: portfolio-db
    plan: free
